import { Project } from "@/types/project";

  export const projects: Project[] = [
    {
      id: 1,
      title: 'Nebula E-commerce',
      description: 'Full-stack e-commerce platform with product management, cart functionality, and payment integration.',
      image: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=2069&auto=format&fit=crop',
      tags: ['Next.js', 'Node.js', 'MongoDB', 'Stripe'],
      demoUrl: 'https://example.com',
      repoUrl: 'https://github.com',
      category: 'fullstack',
    },
    {
      id: 2,
      title: 'Stellar API',
      description: 'RESTful API service with authentication, rate limiting, and comprehensive documentation.',
      image: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?q=80&w=2069&auto=format&fit=crop',
      tags: ['Node.js', 'Express', 'PostgreSQL', 'JWT'],
      demoUrl: 'https://example.com',
      repoUrl: 'https://github.com',
      category: 'backend',
    },
    {
      id: 3, 
      title: 'Orbit Social',
      description: 'Social media platform with real-time messaging, post sharing, and user profiles.',
      image: 'https://images.unsplash.com/photo-1581822261290-991b38693d1b?q=80&w=2070&auto=format&fit=crop',
      tags: ['React', 'Firebase', 'Redux', 'Styled Components'],
      demoUrl: 'https://example.com',
      repoUrl: 'https://github.com',
      category: 'fullstack',
    },
    {
      id: 4,
      title: 'Galaxy Weather',
      description: 'Weather application with location detection, forecasts, and beautiful visualizations.',
      image: 'https://images.unsplash.com/photo-1534996858221-380b92700493?q=80&w=2031&auto=format&fit=crop',
      tags: ['React Native', 'TypeScript', 'Weather API', 'Geolocation'],
      demoUrl: 'https://example.com',
      repoUrl: 'https://github.com',
      category: 'mobile',
    },
    {
      id: 5,
      title: 'Pulsar Analytics',
      description: 'Data analytics platform with interactive dashboards and report generation.',
      image: 'https://images.unsplash.com/photo-1639322537228-f710d846310a?q=80&w=2032&auto=format&fit=crop',
      tags: ['Vue.js', 'D3.js', 'Node.js', 'MongoDB'],
      demoUrl: 'https://example.com',
      repoUrl: 'https://github.com',
      category: 'frontend',
    },
    {
      id: 6,
      title: "Portfolio Website",
      description: "A modern portfolio website with smooth animations and responsive design.",
      image: "https://images.unsplash.com/photo-1547658719-da2b51169166?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      tags: ["Next.js", "Tailwind CSS", "Framer Motion"],
      category: "frontend",
      repoUrl: "https://github.com/Nirbhay007/portfolio-new",
      demoUrl: "#",
    },
    {
      id: 8,
      title: "Task Management App",
      description: "A collaborative task management application with real-time updates and team features.",
      image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      tags: ["React", "Firebase", "Material UI"],
      category: "fullstack",
      repoUrl: "#",
      demoUrl: "#",
    },
    {
      id: 10,
      title: "Blog API",
      description: "A RESTful API for a blog platform with authentication, posts, comments, and user management.",
      image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      tags: ["Node.js", "Express", "MongoDB", "JWT"],
      category: "backend",
      repoUrl: "#",
      demoUrl: "#",
    }
  ];
